spring:
  datasource:
    username: shivam
    password: password
    url: jdbc:mysql://localhost:3306/test1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
